services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      X_SYNC_SECRET_KEY: ${X_SYNC_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
