services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ncu_tldr
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ncu_tldr"]
      interval: 5s
      timeout: 5s
      retries: 20

  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/ncu_tldr
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
