"""create users, departments, teachers, courses table

Revision ID: ee6ea0b7b0bf
Revises:
Create Date: 2026-02-26 21:05:17.587500

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee6ea0b7b0bf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "guide_level",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "credibility_score",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("1.0"),
            nullable=False,
        ),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "total_reviews", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_comments", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credibility_score BETWEEN 0.1 AND 5.0", name="ck_users_credibility_range"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "department_id", name="uq_teachers_name_dept"),
    )
    op.create_index(
        "idx_teachers_department", "teachers", ["department_id"], unique=False
    )
    op.create_index("idx_teachers_name", "teachers", ["name"], unique=False)
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("course_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("credits", sa.SmallInteger(), nullable=False),
        sa.Column("course_type", sa.String(length=20), nullable=False),
        sa.Column("schedule", sa.String(length=100), nullable=True),
        sa.Column("last_offered_semester", sa.String(length=20), nullable=True),
        sa.Column(
            "avg_reward",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "avg_score",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "avg_easiness",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "avg_teacher_style",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "avg_overall",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "review_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_code", "teacher_id", name="uq_courses_code_teacher"
        ),
    )
    op.create_index(
        "idx_courses_avg_overall",
        "courses",
        [sa.literal_column("avg_overall DESC")],
        unique=False,
    )
    op.create_index(
        "idx_courses_department", "courses", ["department_id"], unique=False
    )
    op.create_index("idx_courses_name", "courses", ["name"], unique=False)
    op.create_index("idx_courses_teacher", "courses", ["teacher_id"], unique=False)
    op.create_table(
        "wishes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("course_name", sa.String(length=200), nullable=False),
        sa.Column("teacher", sa.String(length=100), nullable=False),
        sa.Column(
            "vote_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_name", "teacher", name="uq_wishes_name_teacher"),
    )
    op.create_index("idx_wishes_course_id", "wishes", ["course_id"], unique=False)
    op.create_index(
        "idx_wishes_vote_count",
        "wishes",
        [sa.literal_column("vote_count DESC")],
        unique=False,
    )
    op.create_table(
        "wish_votes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("wish_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wish_id"], ["wishes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "wish_id"),
    )
    op.create_index("idx_wish_votes_wish", "wish_votes", ["wish_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_wish_votes_wish", table_name="wish_votes")
    op.drop_table("wish_votes")
    op.drop_index("idx_wishes_vote_count", table_name="wishes")
    op.drop_index("idx_wishes_course_id", table_name="wishes")
    op.drop_table("wishes")
    op.drop_index("idx_courses_teacher", table_name="courses")
    op.drop_index("idx_courses_name", table_name="courses")
    op.drop_index("idx_courses_department", table_name="courses")
    op.drop_index("idx_courses_avg_overall", table_name="courses")
    op.drop_table("courses")
    op.drop_index("idx_teachers_name", table_name="teachers")
    op.drop_index("idx_teachers_department", table_name="teachers")
    op.drop_table("teachers")
    op.drop_table("users")
    op.drop_table("departments")
    # ### end Alembic commands ###
