"""add comments and comment_votes tables

Revision ID: 381b8c6814da
Revises: ee6ea0b7b0bf
Create Date: 2026-03-09 10:30:33.071782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "381b8c6814da"
down_revision: Union[str, Sequence[str], None] = "ee6ea0b7b0bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("likes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "dislikes", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_comments_course_id",
        "comments",
        [sa.literal_column("course_id"), sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_comments_parent_id", "comments", ["parent_id"], unique=False)
    op.create_index("idx_comments_user_id", "comments", ["user_id"], unique=False)
    op.create_table(
        "comment_votes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("vote_type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("vote_type IN (1, -1)", name="ck_comment_votes_vote_type"),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "comment_id"),
    )
    op.create_index(
        "idx_comment_votes_comment", "comment_votes", ["comment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_comment_votes_comment", table_name="comment_votes")
    op.drop_table("comment_votes")
    op.drop_index("idx_comments_user_id", table_name="comments")
    op.drop_index("idx_comments_parent_id", table_name="comments")
    op.drop_index("idx_comments_course_id", table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
